### ISSUE TITLE
8.1: TEB properties vs PGap

### ISSUE THREAD

**Issue by pv33** [ivaROS/PotentialGap#1]
> 1. Regarding the experimental results: 1) Some of the insights you provided in the author response, analyzing TEB’s shortcomings and PG’s advantages (after modifications), should appear in the main paper. A table showing TEB’s problems and showing how the proposed method overcomes them would be more clear.

- [ ] Create Table to put in supplementary material.

**Comment by pv33** [comment]
@Cryptum169 @shiyuF 
TEB has nonholonomic soft constraints. It doesn't factor in "second order dynamics".  Better to just put nonholonomic motion model or something like that.

TEB has a PRM with Homology estimation. Properties should be:

  Homology estimation can be incorrect.
  Resulting roadmap does not fully explore local path space

Should put "Sensor based representation (also called a perception space approach)"

Otherwise Table is fine.  Should put here already.

**Comment by pv33** [comment]
@Cryptum169 @shiyuF 
Might be good to have two tables since they provide information in different ways.  One with TEB (left) and PGap (right), plus another for PGap properties only.

**Comment by Cryptum169** [comment]
Edits are done. The second table feels a bit thin with a single column and I am wondering if keeping them in the same table but adding a double horizontal rule helps show the difference. 
![Screenshot from 2021-07-26 17-34-48](https://user-images.githubusercontent.com/22670525/127062316-48401427-7f7b-4292-92de-4ce3bc45d644.png)

**Comment by pv33** [comment]
@Cryptum169 
Sure, that's fine.

**Comment by Cryptum169** [comment]
@pv33 Got it, it's been moved here.
